# https://cmake.org/cmake/help/v3.10/module/FindOpenGL.html

macro(use_opengl)
  SET(OPENGL_INCLUDE_DIRS "")
  SET(OPENGL_CXX_FLAGS "")
  SET(OPENGL_LDFLAGS "")

  pkg_search_module(OGL REQUIRED gl)
  if(OGL_FOUND)
    list(APPEND OPENGL_INCLUDE_DIRS ${OGL_INCLUDE_DIRS})
    list(APPEND OPENGL_CXX_FLAGS ${OGL_CXX_FLAGS})
    list(APPEND OPENGL_LDFLAGS ${OGL_LDFLAGS})
  endif()


  pkg_search_module(EGL REQUIRED egl)
  if(EGL_FOUND)
    list(APPEND OPENGL_INCLUDE_DIRS ${EGL_INCLUDE_DIRS})
    list(APPEND OPENGL_CXX_FLAGS ${EGL_CXX_FLAGS})
    list(APPEND OPENGL_LDFLAGS ${EGL_LDFLAGS})
  endif()


  pkg_search_module(GLEW REQUIRED glew)
  if(GLEW_FOUND)
    list(APPEND OPENGL_INCLUDE_DIRS ${GLEW_INCLUDE_DIRS})
    list(APPEND OPENGL_CXX_FLAGS ${GLEW_CXX_FLAGS})
    list(APPEND OPENGL_LDFLAGS ${GLEW_LDFLAGS})
  endif()

  pkg_search_module(GLFW REQUIRED glfw3)
  if(GLFW_FOUND)
    list(APPEND OPENGL_INCLUDE_DIRS ${GLFW_INCLUDE_DIRS})
    list(APPEND OPENGL_CXX_FLAGS ${GLFW_CXX_FLAGS})
    list(APPEND OPENGL_LDFLAGS ${GLFW_LDFLAGS})
  endif()


  pkg_search_module(GLM REQUIRED glm)
  if(GLM_FOUND)
    list(APPEND OPENGL_INCLUDE_DIRS ${GLM_INCLUDE_DIRS})
    list(APPEND OPENGL_CXX_FLAGS ${GLM_CXX_FLAGS})
    list(APPEND OPENGL_LDFLAGS ${GLM_LDFLAGS})
  endif()


  #pkg_search_module(ASSIMP REQUIRED assimp)
  #if(ASSIMP_FOUND)
  #  list(APPEND FLEXR_CXX_FLAGS ${ASSIMP_CXX_FLAGS})
  #  list(APPEND FLEXR_LINKER_FLAGS ${ASSIMP_LDFLAGS})
  #endif()

  message(STATUS "OpenGL Family Details")
  message("\t OPENGL_INCLUDE_DIRS: ${OPENGL_INCLUDE_DIRS}")
  message("\t OPENGL_LDFLAGS: ${OPENGL_LDFLAGS}")

  include_directories(${OPENGL_INCLUDE_DIRS})
  list(APPEND FLEXR_CORE_CXX_FLAGS ${OPENGL_CXX_FLAGS})
  list(APPEND FLEXR_CORE_LINKER_FLAGS ${OPENGL_LDFLAGS})

endmacro()

use_opengl()

