macro(core_use_rosbag)
  if(${USE_ROSBAG})
    pkg_search_module(ROSBAG REQUIRED rosbag)
    if(ROSBAG_FOUND)
      add_definitions(-D__FLEXR_USE_ROSBAG__)
      message(STATUS "ROSBAG Details")
      message("\t ROSBAG_INCLUDE_DIRS: ${ROSBAG_INCLUDE_DIRS}")
      message("\t ROSBAG_CXX_FLAGS: ${ROSBAG_CXX_FLAGS}")
      message("\t ROSBAG_LDFLAGS: ${ROSBAG_LDFLAGS}")

      include_directories(${ROSBAG_INCLUDE_DIRS})
      list(APPEND FLEXR_CORE_CXX_FLAGS ${ROSBAG_CXX_FLAGS})
      list(APPEND FLEXR_CORE_INCLUDE_DIRS -I${ROSBAG_INCLUDE_DIRS})
      list(APPEND FLEXR_CORE_LINKER_FLAGS ${ROSBAG_LDFLAGS})
      list(APPEND FLEXR_CORE_LINKER_FLAGS -D__FLEXR_USE_ROSBAG__)
    endif(ROSBAG_FOUND)
  endif(${USE_ROSBAG})
endmacro()

