macro(core_use_yaml_cpp)
  pkg_search_module(YAMLCPP REQUIRED yaml-cpp)
  if(YAMLCPP_FOUND)
    message(STATUS "YAMLCPP Details")
    message("\t YAMLCPP_INCLUDE_DIRS: ${YAMLCPP_INCLUDE_DIRS}")
    message("\t YAMLCPP_CXX_FLAGS: ${YAMLCPP_CXX_FLAGS}")
    message("\t YAMLCPP_LDFLAGS: ${YAMLCPP_LDFLAGS}")

    include_directories(${YAMLCPP_INCLUDE_DIRS})
    list(APPEND FLEXR_CORE_CXX_FLAGS ${YAMLCPP_CXX_FLAGS})
    list(APPEND FLEXR_CORE_INCLUDE_DIRS -I${YAMLCPP_INCLUDE_DIRS})
    list(APPEND FLEXR_CORE_LINKER_FLAGS ${YAMLCPP_LDFLAGS})
  endif(YAMLCPP_FOUND)
endmacro()

